{
 "title": "Monitoring Hidroponik",
 "time": { "from": "2023-06-16T03:59:21.000Z", "to": "2023-06-16T04:24:47.000Z" },
 "panels": [
  {
   "title": "Status Pompa Air",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT msgpompa, waktu FROM fuzzy ORDER BY waktu DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "Status Pompa pH up",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT msgpompaup, waktu FROM fuzzy ORDER BY waktu DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "Status Pompa pH down",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT msgpompadown, waktu FROM fuzzy ORDER BY waktu DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "Fuzzy Pompa Air",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT defuzzypompa, waktu FROM fuzzy ORDER BY waktu DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "Fuzzy Pompa pH Up",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT defuzzyup, waktu FROM fuzzy ORDER BY waktu DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "Fuzzy Pompa pH Down",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT defuzzydown, waktu FROM fuzzy ORDER BY waktu DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "Ketinggian Air",
   "type": "stat",
   "description": "Hasil kalkulasi nilai dari 3 sensor ketinggian air",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT jarak, waktu FROM sensor ORDER BY waktu DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "Grafik Ketinggian Air",
   "type": "timeseries",
   "description": "Grafik nilai ketinggian air yang didapat dari ke-3 sensor HC-SR04",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT jarak, waktu FROM sensor ORDER BY waktu LIMIT 50 "
    }
   ]
  },
  {
   "title": "Ketinggian Air 1",
   "type": "stat",
   "description": "Nilai dari Sensor HC-SR04(1)",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT jarak1, waktu FROM sensor ORDER BY waktu DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "Ketinggian Air 2",
   "type": "stat",
   "description": "Nilai dari Sensor HC-SR04(2)",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT jarak2, waktu FROM sensor ORDER BY waktu DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "Ketinggian Air 3",
   "type": "stat",
   "description": "Nilai dari sensor HC-SR04(3)",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT jarak3, waktu FROM sensor ORDER BY waktu DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "pH",
   "type": "stat",
   "description": "Hasil kalkulasi nilai dari 3 sensor pH",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT ph, waktu FROM sensor ORDER BY waktu DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "Grafik pH",
   "type": "timeseries",
   "description": "Grafik nilai pH yang didapat dari ke-3 sensor E201",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT ph, waktu FROM sensor ORDER BY waktu LIMIT 50 "
    }
   ]
  },
  {
   "title": "pH 1",
   "type": "stat",
   "description": "Nilai dari sensor E201(1)",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT ph1, waktu FROM sensor ORDER BY waktu DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "pH 2",
   "type": "stat",
   "description": "Nilai dari sensor E201(2)",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT ph2, waktu FROM sensor ORDER BY ph2 DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "pH 3",
   "type": "stat",
   "description": "Nilai dari sensor E201(3)",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT ph3, waktu FROM sensor ORDER BY waktu DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "Suhu",
   "type": "stat",
   "description": "Hasil kalkulasi nilai dari 3 sensor suhu",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT suhu, waktu FROM sensor ORDER BY waktu DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "Grafik Suhu",
   "type": "timeseries",
   "description": "Grafik nilai suhu yang didapat dari ketiga sensor DHT22",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT suhu, waktu FROM sensor ORDER BY waktu LIMIT 50 "
    }
   ]
  },
  {
   "title": "Suhu 1",
   "type": "stat",
   "description": "Nilai suhu dari sensor DHT22(1)",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT suhu1, waktu FROM sensor ORDER BY waktu DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "Suhu 2",
   "type": "stat",
   "description": "Nilai suhu dari sensor DHT22(2)",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT suhu2, waktu FROM sensor ORDER BY waktu DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "Suhu 3",
   "type": "stat",
   "description": "Nilai suhu dari sensor DHT22(3)",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT suhu3, waktu FROM sensor ORDER BY waktu DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "Kelembaban",
   "type": "stat",
   "description": "Hasil kalkulasi nilai dari 3 sensor kelembaban",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT kelembaban, waktu FROM sensor ORDER BY waktu DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "Grafik Kelembaban",
   "type": "timeseries",
   "description": "Grafik nilai kelembaban yang didapat dari ketiga sensor DHT22",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "rawSql": "SELECT kelembaban, waktu FROM sensor ORDER BY waktu LIMIT 50 "
    }
   ]
  },
  {
   "title": "Kelembaban 1",
   "type": "stat",
   "description": "Nilai kelembaban dari sensor DHT22(1)",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT kelembaban1, waktu FROM sensor ORDER BY waktu DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "Kelembaban 2",
   "type": "stat",
   "description": "Nilai kelembaban dari sensor DHT22(2)",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT kelembaban2, waktu FROM sensor ORDER BY waktu DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "Kelembaban 3",
   "type": "stat",
   "description": "Nilai kelembaban dari sensor DHT22(3)",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT kelembaban3, waktu FROM sensor ORDER BY waktu DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "Intensitas Cahaya",
   "type": "stat",
   "description": "Hasil kalkulasi nilai dari 3 sensor intensitas cahaya",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT cahaya, waktu FROM sensor ORDER BY waktu DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "Grafik Intensitas Cahaya",
   "type": "timeseries",
   "description": "Grafik nilai intensitas cahaya yang didapat dari ketiga sensor BH1750",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "rawSql": "SELECT cahaya, waktu FROM sensor ORDER BY waktu LIMIT 50 "
    }
   ]
  },
  {
   "title": "Inten Cahaya 1",
   "type": "stat",
   "description": "Nilai dari sensor BH1750(1)",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT cahaya1, waktu FROM sensor ORDER BY waktu DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "Inten Cahaya 2",
   "type": "stat",
   "description": "Nilai dari sensor BH1750(2)",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT cahaya2, waktu FROM sensor ORDER BY waktu DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "Inten Cahaya 3",
   "type": "stat",
   "description": "Nilai dari sensor BH1750(3)",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT cahaya3, waktu FROM sensor ORDER BY waktu DESC LIMIT 1 "
    }
   ]
  }
 ]
}